#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

poetry run black .
# poetry run flake8 .
# poetry run mypy .
poetry run autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place . --exclude=__init__.py
poetry run isort **/*.py
# poetry run pytest --cov-report=html

git add -- .